import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



import { 
  Input, 
  Stack,
  InputGroup, 
  InputLeftAddon, 
  InputRightAddon,   
  Divider , 
  Text, 
} from '@chakra-ui/react'



type CardOps = {  link:string, title: string, desc: string } 

function Card( ops : CardOps) {
    return (
        <a key={ops.link} href={ops.link} className={styles.card}>
          <h2>{ops.title} &rarr;</h2>
          <Divider/>
          <box className={styles.cardContent}>
            <p>{ops.desc}</p>
          </box>
          </a>
    ) ; 
}

const PlaygroundApps = [
    /* 
    { link : "/webrepl" ,
      title  : "Web Repl" ,
      desc : "Connects to a running node repl via the browser and enhances it with UI based functionality (data visualization)"  } ,
    */
    
    { link : "/abx" ,
      title : "Antibiosis",
      desc : "Antibiotic Visualization Application" } , 
    
]

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <a href="">Web Playground</a>
        </h1>

        <p className={styles.description}>
          The web playground is for rapid protyping of web applications and UI components. 
        </p>

        <div className={styles.grid}>
          {PlaygroundApps.map( (x: CardOps) => Card(x) ) }
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/sheunaluko"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Sheun Aluko

        </a>
      </footer>
    </div>
  )
}

export default Home
